version: "3"

services:
  db:
    image: rafanetow/node-test:latest
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=baasu.db.elephantsql.com
      -  TYPEORM_USERNAME=ssthczxc
      - TYPEORM_PASSWORD=BEz0jJlx4CklukuWb9CFqGHWG6pDlUcn
      - TYPEORM_DATABASE=ssthczxc
      - TYPEORM_PORT=5432
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_LOGGING=false
      - TYPEORM_ENTITIES=src/modules/**/*Entity.{ts,js},dist/modules/**/*Entity.{ts,js}
      - TYPEORM_MIGRATIONS=src/migrations/*.{ts,js},dist/migrations/*.js
      - TYPEORM_MIGRATIONS_DIR=src/migrations/*.{ts,js},dist/migrations/*.js
